# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kv2 < Formula
  desc ""
  homepage "https://git.huggins.io/kv2"
  version "0.11.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hugginsio/kv2/releases/download/v0.11.5/kv2_darwin_amd64.tar.gz"
      sha256 "4f49d779955b0766c406742a6eb481991be63652fef21f81363e90eef34424b0"

      def install
        bin.install "kv2"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hugginsio/kv2/releases/download/v0.11.5/kv2_darwin_arm64.tar.gz"
      sha256 "710f86c87d24ddbbd051e7708fc12882b68d37dcac34375c0730e20a23dd2d3c"

      def install
        bin.install "kv2"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hugginsio/kv2/releases/download/v0.11.5/kv2_linux_amd64.tar.gz"
        sha256 "878947705a33a28a8eb1f5024795b0b0e14c944cef9f68b2a4795126f2b37460"

        def install
          bin.install "kv2"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hugginsio/kv2/releases/download/v0.11.5/kv2_linux_arm64.tar.gz"
        sha256 "210e20ce272a4f2677514beb5afc261139aab0cf24f10f8d485ca53a0913019d"

        def install
          bin.install "kv2"
        end
      end
    end
  end

  test do
    system "#{bin}/kv2 --help"
  end
end
