# This file was generated by GoReleaser. DO NOT EDIT.
cask "talosctx" do
  name "talosctx"
  desc "Faster context switching for `talosctl`"
  homepage "https://huggins.dev/talosctx"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "talosctx"
  fish_completion "completions/talosctx.fish"

  on_macos do
    on_intel do
      url "https://github.com/hugginsio/talosctx/releases/download/v#{version}/talosctx_darwin_amd64.tar.gz"
      sha256 "89d5c639d41ba5eaaa9a6b829f80ee83bb85cbebffb1146fdd67776d7ce4f16c"
    end
    on_arm do
      url "https://github.com/hugginsio/talosctx/releases/download/v#{version}/talosctx_darwin_arm64.tar.gz"
      sha256 "dd777df7408d6461f0ec8bd917e83c454bd056c3e4d4bf1fb3cc6c763c70025a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/hugginsio/talosctx/releases/download/v#{version}/talosctx_linux_amd64.tar.gz"
      sha256 "a482b14242b1654f8189ade1ac2161b4e88671343baef5190997e0599009e80a"
    end
    on_arm do
      url "https://github.com/hugginsio/talosctx/releases/download/v#{version}/talosctx_linux_arm64.tar.gz"
      sha256 "053919c55cdf88150ba1e9cf88db0346f4bc707e5bd7a4e75d545e03349730b1"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/talosctx"]
    end
  end

  # No zap stanza required
end
