# This file was generated by GoReleaser. DO NOT EDIT.
cask "talosctx" do
  name "talosctx"
  desc "Faster context switching for `talosctl`"
  homepage "https://huggins.dev/talosctx"
  version "0.2.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "talosctx"
  fish_completion "completions/talosctx.fish"

  on_macos do
    on_intel do
      url "https://github.com/hugginsio/talosctx/releases/download/v#{version}/talosctx_darwin_amd64.tar.gz"
      sha256 "191017eafde7ce506e05417d6c0151dee4b0c82d32d0e7240335c0b6a630faca"
    end
    on_arm do
      url "https://github.com/hugginsio/talosctx/releases/download/v#{version}/talosctx_darwin_arm64.tar.gz"
      sha256 "83fa63627dfc1dd5581ae08a48ebd5bc413e795b8dae8e42f83b7d6848df1c18"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/hugginsio/talosctx/releases/download/v#{version}/talosctx_linux_amd64.tar.gz"
      sha256 "def3b16f3d11e85b47676f843ab74dad6c545a5ad35d5f4c5ed119b9682b5b3e"
    end
    on_arm do
      url "https://github.com/hugginsio/talosctx/releases/download/v#{version}/talosctx_linux_arm64.tar.gz"
      sha256 "af8e61e0b7d9b9bb7898f576b82f92e0595df806fdf113f4aea9cd00a207d7b9"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/talosctx"]
    end
  end

  # No zap stanza required
end
