# This file was generated by GoReleaser. DO NOT EDIT.
cask "talosctx" do
  name "talosctx"
  desc "Faster context switching for `talosctl`"
  homepage "https://huggins.dev/talosctx"
  version "0.1.8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "talosctx"

  on_macos do
    on_intel do
      url "https://github.com/hugginsio/talosctx/releases/download/v#{version}/talosctx_darwin_amd64.tar.gz"
      sha256 "efe61b72e856500f5b78d92d7b589f28adf078af619e6cf371381cba7f5725ff"
    end
    on_arm do
      url "https://github.com/hugginsio/talosctx/releases/download/v#{version}/talosctx_darwin_arm64.tar.gz"
      sha256 "3699170ca243981ba59308e57a796c3ff92445820845c0f837dff44fa360b651"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/hugginsio/talosctx/releases/download/v#{version}/talosctx_linux_amd64.tar.gz"
      sha256 "790b92da7fa47fffc2a29ffb2d212e20c5003335c7c6c791c9eb4c437c97e77a"
    end
    on_arm do
      url "https://github.com/hugginsio/talosctx/releases/download/v#{version}/talosctx_linux_arm64.tar.gz"
      sha256 "1336c6d61406e8002a632c137bf336373f1dcb908e6513e04b697d423de95a76"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/talosctx"]
    end
  end

  # No zap stanza required
end
