# This file was generated by GoReleaser. DO NOT EDIT.
cask "taskkit" do
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/hugginsio/taskkit/releases/download/v#{version}/taskkit_darwin_amd64.tar.gz"
      sha256 "8e0958c074959f66fd31018471d38b5cbf46093a6bd26b777528f9c39dd481e2"
    end
    on_arm do
      url "https://github.com/hugginsio/taskkit/releases/download/v#{version}/taskkit_darwin_arm64.tar.gz"
      sha256 "bf332eb41eb57bca6e40e59dccfb9e0fc09281c2eb878cc5eac0e7ad20dd82ba"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/hugginsio/taskkit/releases/download/v#{version}/taskkit_linux_amd64.tar.gz"
      sha256 "d4cc95ce6c5e627984803c41e44317104e0866c0e5d0487e08e2615114bc4d1b"
    end
    on_arm do
      url "https://github.com/hugginsio/taskkit/releases/download/v#{version}/taskkit_linux_arm64.tar.gz"
      sha256 "e9404d2f83b93087d1f1393c808c433c14a26d7e2d98618ba2a82f7b08a67354"
    end
  end

  name "taskkit"
  desc "A toolkit for task and project management"
  homepage "https://huggins.dev/taskkit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "taskkit"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/taskkit"]
    end
  end

  # No zap stanza required

end
