# This file was generated by GoReleaser. DO NOT EDIT.
cask "taskkit" do
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/hugginsio/taskkit/releases/download/v#{version}/taskkit_darwin_amd64.tar.gz"
      sha256 "0e43f4dcb2e58d1d1bfb43f3fcb1b8209563628e4884515499328e2bb9e1673b"
    end
    on_arm do
      url "https://github.com/hugginsio/taskkit/releases/download/v#{version}/taskkit_darwin_arm64.tar.gz"
      sha256 "72ee52cef5323b76d4e3556f81ca713ef2af274120b250ccedd219f8f5714d43"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/hugginsio/taskkit/releases/download/v#{version}/taskkit_linux_amd64.tar.gz"
      sha256 "5f6425fc3407c7e5acd04e489deecc2e1576e18a5180a092456d652a2b723a48"
    end
    on_arm do
      url "https://github.com/hugginsio/taskkit/releases/download/v#{version}/taskkit_linux_arm64.tar.gz"
      sha256 "6c7d773aef82027f2ae0b5d7d07df32f4d9a876447bc51177c73a63540304610"
    end
  end

  name "taskkit"
  desc "A toolkit for task and project management"
  homepage "https://huggins.dev/taskkit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "taskkit"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/taskkit"]
    end
  end

  # No zap stanza required

end
