# This file was generated by GoReleaser. DO NOT EDIT.
cask "taskkit" do
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/hugginsio/taskkit/releases/download/v#{version}/taskkit_darwin_amd64.tar.gz"
      sha256 "b347583a2796dc953063f8a07390d99c037de974b0ed79d4799b4ffd977a6666"
    end
    on_arm do
      url "https://github.com/hugginsio/taskkit/releases/download/v#{version}/taskkit_darwin_arm64.tar.gz"
      sha256 "2fb38c34ef16379c1e2c3e9e55b3379bf9253a038191cfa85e3ed6237a0d1162"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/hugginsio/taskkit/releases/download/v#{version}/taskkit_linux_amd64.tar.gz"
      sha256 "d3ebbaaff03437d0c59d4dde597dd66097aac943d62ab4418e43c33072fa8923"
    end
    on_arm do
      url "https://github.com/hugginsio/taskkit/releases/download/v#{version}/taskkit_linux_arm64.tar.gz"
      sha256 "2ce07139d787a3f38025e6a8c19734a63b6c33545aff4cb8231ba42fb9a7ef88"
    end
  end

  name "taskkit"
  desc "A toolkit for task and project management"
  homepage "https://huggins.dev/taskkit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "taskkit"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/taskkit"]
    end
  end

  # No zap stanza required

end
