# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dev < Formula
  desc ""
  homepage "https://huggins.dev/dev"
  version "1.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hugginsio/dev/releases/download/v1.2.0/dev_darwin_amd64.tar.gz"
      sha256 "201ad86ba8ab6fd6e2c727406f5a1d09acd01353b79117dc18162754a2e59225"

      def install
        bin.install "dev"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hugginsio/dev/releases/download/v1.2.0/dev_darwin_arm64.tar.gz"
      sha256 "b94b570dba8653f4ddb8024ac9d9dba44570890f1d1571a2dc13683cd4234bd8"

      def install
        bin.install "dev"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/hugginsio/dev/releases/download/v1.2.0/dev_linux_amd64.tar.gz"
      sha256 "5a1445bc96d169c95b94a0876f6d4f5179f6f2c149035ffa5a7cc2bd0b50d699"
      def install
        bin.install "dev"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/hugginsio/dev/releases/download/v1.2.0/dev_linux_arm64.tar.gz"
      sha256 "5db185f351180d77d565cf230f7e681b976fdf6613bb016b52b3ac0365456362"
      def install
        bin.install "dev"
      end
    end
  end

  test do
    system "#{bin}/dev -h"
  end
end
