# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dev < Formula
  desc ""
  homepage "https://huggins.dev/dev"
  version "1.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hugginsio/dev/releases/download/v1.0.1/dev_darwin_amd64.tar.gz"
      sha256 "509e7a40f7dfaff8d22622e88b046dc9799e6a2ca76823e586202d6e6902055a"

      def install
        bin.install "dev"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hugginsio/dev/releases/download/v1.0.1/dev_darwin_arm64.tar.gz"
      sha256 "76cdd762900cfb676b5c6ed5a8c6ee2486dbb0398fd7d5c1d3c900496fd2cbf2"

      def install
        bin.install "dev"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/hugginsio/dev/releases/download/v1.0.1/dev_linux_amd64.tar.gz"
      sha256 "4b15fd9debfe7daabb4939d1f198a769a351cfa5475d5cc159affc656c25ec59"
      def install
        bin.install "dev"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/hugginsio/dev/releases/download/v1.0.1/dev_linux_arm64.tar.gz"
      sha256 "bafb3a802e847bb79d23ff86dca87d1352820916f0464a772053e92864871f5a"
      def install
        bin.install "dev"
      end
    end
  end

  test do
    system "#{bin}/dev -h"
  end
end
