# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dev < Formula
  desc ""
  homepage "https://huggins.dev/dev"
  version "1.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hugginsio/dev/releases/download/v1.1.0/dev_darwin_amd64.tar.gz"
      sha256 "edd2bb3801c4277952e0e1eb1bf0a41bb3d4dd956e9ceea5ae4ee83b4d400289"

      def install
        bin.install "dev"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hugginsio/dev/releases/download/v1.1.0/dev_darwin_arm64.tar.gz"
      sha256 "a03e68ca400228f9b5b02ba3c2c979ef6a518968da2c0c34e497524eaf22dd18"

      def install
        bin.install "dev"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/hugginsio/dev/releases/download/v1.1.0/dev_linux_amd64.tar.gz"
      sha256 "3eeba3ea532dc6cd913c38327f34150d888d33042729cd4af12b1c17e27cafcc"
      def install
        bin.install "dev"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/hugginsio/dev/releases/download/v1.1.0/dev_linux_arm64.tar.gz"
      sha256 "e84e60e76c989fa3a8881ec100ed65bdfab05b88cbf0d69596b30f62338b675e"
      def install
        bin.install "dev"
      end
    end
  end

  test do
    system "#{bin}/dev -h"
  end
end
