# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitVwi < Formula
  desc "Git add-on for opening work item details in your browser based on the current branch."
  homepage "https://go.huggins.io/prj/git-view-work-item"
  version "1.5.0"
  license "BSD-2-Clause"

  depends_on "git"
  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/hugginsio/git-view-work-item/releases/download/v1.5.0/git-vwi_darwin_arm64.tar.gz"
      sha256 "7f904b90455449a2fbb8b19580ccb47dacdd26b67a98ee5c320e4867c68b3cb5"

      def install
        bin.install "git-vwi"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hugginsio/git-view-work-item/releases/download/v1.5.0/git-vwi_darwin_amd64.tar.gz"
      sha256 "46740d4741016a85dd5c481fa5f58d91453960d786da7e6a276251cfb20fab2f"

      def install
        bin.install "git-vwi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hugginsio/git-view-work-item/releases/download/v1.5.0/git-vwi_linux_arm64.tar.gz"
      sha256 "37ba6fb1b0c6b1e1e2281e84295aab3dc89b0b45aa65a6812a745c531145f478"

      def install
        bin.install "git-vwi"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hugginsio/git-view-work-item/releases/download/v1.5.0/git-vwi_linux_amd64.tar.gz"
      sha256 "98ccaf03a486665e2991b353870ee6d3c3c583a05a3384ecd12855b6c5034202"

      def install
        bin.install "git-vwi"
      end
    end
  end

  test do
    system "#{bin}/git-vwi version"
  end
end
