# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kv2 < Formula
  desc ""
  homepage "https://git.huggins.io/kv2"
  version "0.11.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hugginsio/kv2/releases/download/v0.11.6/kv2_darwin_amd64.tar.gz"
      sha256 "30e77da140ef8ba4bd0ba8efe1f64036490e9ea013d6e6bb6e3fccfb229474ff"

      def install
        bin.install "kv2"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hugginsio/kv2/releases/download/v0.11.6/kv2_darwin_arm64.tar.gz"
      sha256 "f48c3256e2f1aa8d644f717ca48b7c16dcefa692bfac834614b72b3161e0cd98"

      def install
        bin.install "kv2"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hugginsio/kv2/releases/download/v0.11.6/kv2_linux_amd64.tar.gz"
        sha256 "5eebf9638b3f42acdd3354a7a8e5075810190cf8e2339fbf5ccc11336f45e51b"

        def install
          bin.install "kv2"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hugginsio/kv2/releases/download/v0.11.6/kv2_linux_arm64.tar.gz"
        sha256 "55a21ebf55da03caaa388b0b42e341a464172987e603dd00717b6bb9eedaed0f"

        def install
          bin.install "kv2"
        end
      end
    end
  end

  test do
    system "#{bin}/kv2 --help"
  end
end
