# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kv2 < Formula
  desc ""
  homepage "https://git.huggins.io/kv2"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hugginsio/kv2/releases/download/v1.0.0/kv2_darwin_amd64.tar.gz"
      sha256 "30cc569ab90bfa59b02fcb77d25f5376c618632e950739ffb4feab263589e2b5"

      def install
        bin.install "kv2"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hugginsio/kv2/releases/download/v1.0.0/kv2_darwin_arm64.tar.gz"
      sha256 "4db5fd9bbf4fbc8f2be895e32817ad23efdf9a16a0ad40762437c15742c614ac"

      def install
        bin.install "kv2"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hugginsio/kv2/releases/download/v1.0.0/kv2_linux_amd64.tar.gz"
        sha256 "8ac85932fd16c6bf5070a4412396ea9d6609c1bad2652fe48b2f74470365da8a"

        def install
          bin.install "kv2"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hugginsio/kv2/releases/download/v1.0.0/kv2_linux_arm64.tar.gz"
        sha256 "cbd96c637ce02089882ba29bc024f4cfaef7a81bad7dbb6b7a234ce93a6f1877"

        def install
          bin.install "kv2"
        end
      end
    end
  end

  test do
    system "#{bin}/kv2 --help"
  end
end
