# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: ci
on:
  push:
  pull_request:
jobs:
  gen-readme:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Generate README
        run: bash ${GITHUB_WORKSPACE}/.github/scripts/gen_readme.sh
      - name: Update README
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore(build): auto-generate README"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
