# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: ci
on:
  push:
  pull_request:
jobs:
  gen-readme:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Generate README
        run: bash ${GITHUB_WORKSPACE}/.github/scripts/gen_readme.sh
